version: "1.0"
services:
  db:
    container_name: "design_smart_home"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=design_smart_home
    ports:
      - "5437:5432"
    networks:
      - custom
  db_test:
    container_name: "design_smart_home_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=design_smart_home_test
    ports:
      - "5438:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge